name: 🐛 Bug Report
description: Ziņo par kļūdu projektā
title: "[Bug] "
labels: bug
body:

  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are affected?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
    validations:
      required: true

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      placeholder: Tell us what you see!
      value: |
        ## 📍 Soļi, lai atkārtotu kļūdu
        1. Ej uz '...'
        2. Klikšķini uz '...'
        3. Pamanīsi, ka '...'

        ## 🖥️ Sagaidāmais rezultāts
        Kas bija paredzēts, lai notiktu?

        ## 📸 Ekrānuzņēmumi (ja iespējams)
        Ja attiecas, pievieno attēlus.


    validations:
      required: true
